project:
  type: website

website:
  title: "Syed Ahmad Zaki"
  site-url: ""
  description: "This is Syed Ahmad Zaki's personal portfolio."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: books.qmd
        text: Books
      
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/syed-ahmad-zaki-bin-syed-sakaf-al-attas/
      - icon: envelope
        href: mailto:syedahmadzaki@yahoo.com.sg
      - icon: github
        href: https://github.com/syedahmadzaki
format:
  html:
    theme: theme.scss
    mainfont: lato
    css: styles.css
    toc: false
    toc_float: false
    

editor: visual

